no_cuda: False
no_mps: False
dry_run: False
seed: 1

logging:
    mlflow_params:
        tracking_uri: 'http://127.0.0.1:5000'
        name: 'MNIST_EXP'

hyperparams:
    batch_size: 2
    test_batch_size: 2
    epochs: 10
    lr: 1.0
    gamma: 0.7

dataset:
    path_train_split: 'data/processed/test_split.csv'
    path_test_split: 'data/processed/test_split.csv'

tracking:
    log_interval: 10

model:
    save: True
    path: 'mnist_cnn.pt'
